Repository TeamDMU/DMU-Android, pull requests merged in 2022-08, with the labels that each got.

#71 Docs : 이슈 및 PR 템플릿 생성 및 적용
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ SETTING, ✍️ DOCS

#73 Feature : Github actions
  .github/workflows/android.yml
  app/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ⚙️ SETTING, 😊 DEVELOP

#74 Docs : README
  LICENSE
  README.md
Labels: ✍️ DOCS

#76 Refactor : 네트워크 세팅 및 NULL 처리 관련 리팩터링
  app/build.gradle
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/SharedPreference.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/DetailService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/NoticeService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/ScheduleService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DetailRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/KeywordRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/ScheduleRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/SettingRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/SplashRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/MyApplication.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/ErrorResponseHandler.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/NetworkError.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/NetworkResult.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/AlarmAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/LoadingDialog.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTORING

#77 Fix : PR이 닫히면 이슈도 함께 닫히도록 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✍️ DOCS

#79 Feature : 폰트 시스템 적용
  app/src/main/assets/pretendard_regular.otf
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/res/font-v26/pretendard.xml
  app/src/main/res/font/pretendard.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_depart.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/layout/item_depart.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/layout/item_image.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/layout/item_schedule.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨 DESIGN, 🤗 FEATURE

#82 Feat : Timber 라이브러리 의존성 추가
  app/build.gradle
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/MyApplication.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/UtilExt.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
Labels: ⚙️ SETTING

#83 Fix : 키워드 화면 진입 시 기존 등록했던 키워드가 체크되지 않는 현상 해결
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
Labels: 🐛 BUG

#84 Feat : 오늘의 식단 UI
  README.md
  app/build.gradle
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/CafeteriaAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/CafeteriaEmployeeAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_menu_cafeteria.xml
  app/src/main/res/drawable/ic_timer.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/item_cafeteria_menu.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: 🎨 DESIGN, 🤗 FEATURE

#85 Fix : FCM 관련 수정사항 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/MyApplication.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/UtilExt.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
Labels: 🤗 FEATURE

#88 Feature : 오늘의 식단 화면 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/standard/MyApplication.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/CafeteriaEmployeeAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaContainer.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CalendarInterface.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/util/ResourceProvider.kt
  app/src/main/res/drawable-xxxhdpi/ic_arrow_right.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_cafeteria.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/item_cafeteria_menu.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/layout/item_schedule.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: 🤗 FEATURE

#90 Fix : 안드로이드 12 스플래시 대응 및 로고, 앱 이름 변경
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/DepartAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
  app/src/main/res/drawable-hdpi/ic_notification.png
  app/src/main/res/drawable-mdpi/ic_notification.png
  app/src/main/res/drawable-v24/ic_launcher_background.xml
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable-xhdpi/ic_notification.png
  app/src/main/res/drawable-xxhdpi/ic_notification.png
  app/src/main/res/drawable-xxxhdpi/ic_notification.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/item_cafeteria_menu.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 🐛 BUG, 🎨 DESIGN

#93 Fix : 로딩 관련 각종 오류 수정
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/BindingAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/LoadingDialog.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_cafeteria.xml
Labels: 🐛 BUG

#94 Feat : Lottie 로딩 다이얼로그 적용
  app/build.gradle
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/raw/loading.json
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN

#97 Feature : UX 개선을 위한 에러 화면 수정
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
  app/src/main/res/drawable-hdpi/bg_button_main_radius.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/values/strings.xml
Labels: 🤗 FEATURE

#100 Refactor : Jetpack Navigation 적용
  app/build.gradle
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/util/KeepStateNavigator.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/dmu_navigation.xml
Labels: ♻️ REFACTORING

#103 Fix : 이벤트 중복 발생 현상, 에러 화면이 반응형으로 나타나지 않는 현상 수정
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeTabType.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/util/Event.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/util/ToastUtil.kt
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/standard_error.xml
  app/src/main/res/layout/standard_no_data.xml
Labels: 🐛 BUG

#105 Feat : 오픈소스 라이센스 화면 UI 및 로직 구성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/entity/OpenSourceEntity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/LicenseAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/license/LicenseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/license/LicenseClickListener.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/license/LicenseViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_depart.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/activity_license.xml
  app/src/main/res/layout/item_license.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 🤗 FEATURE
