Repository TeamDMU/DMU-Android, pull requests merged in 2022-06, with the labels that each got.

#45 Feat : Pick keyword to FCM subscribe, Room
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/UserDatabase.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/dao/UserDao.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/entity/KeywordEntity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/KeywordRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/MyApplication.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/res/color/bg_chip_select.xml
  app/src/main/res/color/bg_chip_text_select.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: setting, develop

#48 Design : Setting
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: design, develop

#50 Feat : UX improvements
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/entity/Department.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DetailRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/KeywordRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/ScheduleRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/BindingAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/NoticeAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: design, develop

#52 Feat : Checking first launch
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/SharedPreference.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/KeywordRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/SplashRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/BindingAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashViewModel.kt
  app/src/main/res/layout/activity_depart.xml
  app/src/main/res/layout/activity_keyword.xml
Labels: develop

#53 Fix : Backstack error
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/res/layout/item_schedule.xml
Labels: bug, develop

#56 Feat : FCM - Setting screen supplementation
  .gitignore
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/SharedPreference.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/ScheduleRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/SettingRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/Department.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/Mapping.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/BindingAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
  app/src/main/res/layout/fragment_setting.xml
Labels: develop

#57 Feat : Alarm List Screen Implementation
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/UserDatabase.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/dao/AlarmDao.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/dao/KeywordDao.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/entity/AlarmEntity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/AlarmRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/KeywordRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/Mapping.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/AlarmAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/BindingAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmClickListener.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/res/drawable-xxxhdpi/ic_arrow_right.xml
  app/src/main/res/drawable/ic_logo_splash.png
  app/src/main/res/drawable/ic_no_data.xml
  app/src/main/res/drawable/ic_splash_logo.png
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/layout/item_file.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design, develop

#63 Design : Splash & Icon
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_splash_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_main.png
  app/src/main/res/mipmap-hdpi/ic_main_foreground.png
  app/src/main/res/mipmap-hdpi/ic_main_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_main.png
  app/src/main/res/mipmap-mdpi/ic_main_foreground.png
  app/src/main/res/mipmap-mdpi/ic_main_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_main.png
  app/src/main/res/mipmap-xhdpi/ic_main_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_main_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_main.png
  app/src/main/res/mipmap-xxhdpi/ic_main_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_main_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_main.png
  app/src/main/res/mipmap-xxxhdpi/ic_main_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_main_round.png
Labels: design, develop

#64 Fix : Incorrect data save in alarm list
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/res/values/strings.xml
Labels: bug, develop
