Repository TeamDMU/DMU-Android, pull requests merged in 2024-01, with the labels that each got.

#129 build : 트레일링 콤마
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Cafeteria.kt
Labels: ♻️ REFACTORING

#133 Setting : 7.4.2 버전 업데이트
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: ⚙️ SETTING

#135 design : 피그마 색상 등록
  app/src/main/res/values/colors.xml
Labels: 🎨 DESIGN, 🩵희우
