Repository TeamDMU/DMU-Android, pull requests merged in 2024-04, with the labels that each got.

#217 Feat : 최초 어플 실행 작업 및 토큰 등록
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/SharedPreference.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Token.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/TokenService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/KeywordRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/MainRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/Constants.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/Department.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/OnboardingKeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
  app/src/main/res/layout/activity_onboarding_permission.xml
Labels: 🤗 FEATURE, 🩵희우

#225 Feat : 1차 QA 반영
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/UtilExt.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/viewholder/NoticeViewHodler.kt
  app/src/main/res/drawable/ic_search_empty.xml
  app/src/main/res/drawable/ic_symbol.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 💛명지

#222 Design : 온보딩 화면 QA 적용
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/OnboardingDepartAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/OnboardingKeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/OnboardingPermissionActivity.kt
  app/src/main/res/color/bg_chip_stroke_select.xml
  app/src/main/res/drawable/bg_radius_100dp.xml
  app/src/main/res/drawable/bg_stroke_blue300_radius_2dp.xml
  app/src/main/res/drawable/bg_stroke_gray300_radius_2dp.xml
  app/src/main/res/drawable/btn_gray300_radius_10dp.xml
  app/src/main/res/layout/activity_depart.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/activity_onboarding_depart.xml
  app/src/main/res/layout/activity_onboarding_keyword.xml
  app/src/main/res/layout/activity_onboarding_permission.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/layout/item_cafeteria_menu.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/layout_onboarding_step.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 🩵희우

#226 Feat : 알림 권한 설정 다이어로그
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/dialog_permission.kt
  app/src/main/res/layout/dialog_permission.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 🩵희우

#228 Fix : 키워드 화면 intent 위치 수정
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
Labels: 🩵희우, 🔥HOTFIX

#231 Design: 2차 QA 반영
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaContainer.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
  app/src/main/res/color/bg_chip_select.xml
  app/src/main/res/layout/activity_onboarding_depart.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨 DESIGN, 🩵희우

#232 Feat : 2차 QA 반영
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/PermissionDialog.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
Labels: 🤗 FEATURE, 💛명지

#234 Refactor : 일품 및 빈 식단
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🐛 BUG, ♻️ REFACTORING, 🩵희우

#237 Fix : 식단 API 오류 수정
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
Labels: 🩵희우, 🔥HOTFIX

#235 Fix : QA 반영
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
  app/src/main/res/values/themes.xml
  build.gradle
Labels: 💛명지

#240 Fix : 설정 내 알람 스위치 상태 동기화 처리
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/PermissionDialog.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: 🐛 BUG

#241 Refactor : 권한 다이어로그 수정
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/PermissionDialog.kt
  app/src/main/res/layout/dialog_permission.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTORING, 🩵희우

#243 Fix : 학과 변경 후에도 이전 학과의 공지사항이 출력되던 오류 수정
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
Labels: 🐛 BUG

#247 Design : 바텀 네비 위 고정 여백 디자인 수정
  app/src/main/res/layout/fragment_cafeteria.xml
Labels: 🎨 DESIGN, 💛명지

#249 Hotfix : 자동화, 로봇 학과 바껴서 출력되는 이슈 해결
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/util/Department.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
Labels: 💛명지, 🔥HOTFIX
