Repository TeamDMU/DMU-Android, pull requests merged in 2024-02, with the labels that each got.

#139 Feat : 바텀 네비게이션에 검색 아이템 추가
  .github/PULL_REQUEST_TEMPLATE.md
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
  app/src/main/res/drawable-v24/ic_menu_calendar.xml
  app/src/main/res/drawable-v24/ic_menu_setting.xml
  app/src/main/res/drawable/ic_menu_cafeteria.xml
  app/src/main/res/drawable/ic_menu_calendar.xml
  app/src/main/res/drawable/ic_menu_home.xml
  app/src/main/res/drawable/ic_menu_search.xml
  app/src/main/res/drawable/ic_menu_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/dmu_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 💛명지

#141 Design : 공지사항 뷰 작업
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/res/drawable-v24/ic_alarm.xml
  app/src/main/res/drawable-v24/ic_back.xml
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 💛명지

#143 Design : 첨부파일 제외 상세보기 뷰 리디자인
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/res/drawable/bg_radius_100dp.xml
  app/src/main/res/drawable/ic_popup.xml
  app/src/main/res/layout/activity_detail.xml
Labels: 🎨 DESIGN, 💛명지

#156 Design : 식단 화면 리디자인
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaContainer.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/item_cafeteria_menu.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🤗 FEATURE, 🩵희우

#137 Design : 온보딩 1단계 학과 선택 페이지의 리디자인
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/res/drawable/bg_search_white_radius_10dp.xml
  app/src/main/res/drawable/btn_gray_to_blue_10dp_enabled.xml
  app/src/main/res/drawable/btn_main_stroke_main_radius_8dp.xml
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/layout/activity_depart.xml
  app/src/main/res/layout/layout_onboarding_step.xml
  app/src/main/res/layout/standard_error.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 🩵희우

#148 Design : 검색 뷰 디자인 및 ux 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/util/KeyboardUtil.kt
  app/src/main/res/drawable/bg_blue100_radius_6dp.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_clear.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 💛명지

#154 Design : 온보딩 2단계 키워드 선택 페이지의 리디자인
  app/src/main/java/com/dongyang/android/youdongknowme/function/SetSpanText.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/res/color/bg_chip_select.xml
  app/src/main/res/color/bg_chip_text_select.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨 DESIGN, 🩵희우

#163 Design : 바텀 네비게이션 폰트 적용
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/styles.xml
Labels: 🎨 DESIGN, 💛명지

#153 Design : 키워드 알림함 리디자인
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/AlarmAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/license/LicenseActivity.kt
  app/src/main/res/drawable-xxxhdpi/ic_arrow_right.xml
  app/src/main/res/drawable/bg_stroke_gray300_radius_10dp.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/layout/standard_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 💛명지

#170 Design : 스플래시 화면 리디자인
  app/src/main/res/drawable/ic_logo_text.xml
  app/src/main/res/drawable/ic_splash.xml
  app/src/main/res/drawable/ic_splash_logo.png
  app/src/main/res/drawable/ic_symbol.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values-v31/themes.xml
Labels: 🎨 DESIGN, 🩵희우

#167 Feat : 대학/학과 공지 뷰 api 연결 및 무한 스크롤 적용
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Notice.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/NoticeService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/NoticeAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/values/strings.xml
Labels: 🤗 FEATURE, 💛명지

#168 Feat : 공지사항 단 건 조회 웹 뷰 구현
  app/build.gradle
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Notice.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/DetailService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DetailRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/FileAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ImageAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/NoticeAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailClickListener.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeClickListener.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/viewholder/NoticeViewHodler.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_file.xml
Labels: 🤗 FEATURE, 💛명지
