Repository TeamDMU/DMU-Android, pull requests merged in 2024-03, with the labels that each got.

#177 Feat : 검색 기능 구현 (페이지네이션 제외)
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/NoticeService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/NoticeAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
Labels: 🤗 FEATURE, 💛명지

#188 fix : 네트워크 url 및 보안 이슈 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/res/xml/network_security_config.xml
Labels: 🐛 BUG, 💛명지

#173 Feat : 웹 뷰 파일 다운로드 구현
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🤗 FEATURE, 💛명지

#186 Feat : 온보딩 3단계 키워드 알림 설정 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/OnboardingKeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
  app/src/main/res/drawable/ic_alarm_fill.xml
  app/src/main/res/layout/activity_keyword.xml
  app/src/main/res/layout/activity_onboarding_permission.xml
  app/src/main/res/values/strings.xml
Labels: 🤗 FEATURE, 🩵희우

#191 Feat : 디자인 QA 공지사항 부분
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_menu_cafeteria.xml
  app/src/main/res/drawable/ic_menu_calendar.xml
  app/src/main/res/drawable/ic_menu_setting.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/raw/loading.json
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 💛명지

#172 Feat : 학사 일정 api 수정
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Cafeteria.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Schedule.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/CafeteriaService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/ScheduleService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/item_schedule.xml
  app/src/main/res/values/themes.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 🩵희우

#190 Feat : 검색 화면 페이지네이션
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
Labels: 🤗 FEATURE, 💛명지

#158 Feat : 식단 api 수정
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Cafeteria.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/CafeteriaService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CalendarInterface.kt
Labels: 🤗 FEATURE, 🩵희우

#193 Feat : 알림 권한 설정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashViewModel.kt
  app/src/main/res/layout/activity_onboarding_permission.xml
Labels: 🤗 FEATURE, 🩵희우

#195 Fix : baseURL 숨김 처리
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
Labels: ⚙️ SETTING, 💛명지

#192 Feat : FCM 연동 및 테스트
  app/build.gradle
  app/google-services.json
  app/src/main/assets/pretendard_regular.otf
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
Labels: 🤗 FEATURE, 💛명지

#198 Hotfix : 컴파일 에러 수정
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
Labels: 💛명지, 🔥HOTFIX

#203 Design : 학사 일정 디자인 QA 반영
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/layout/fragment_schedule.xml
  app/src/main/res/layout/item_schedule.xml
  app/src/main/res/values/themes.xml
Labels: 🎨 DESIGN, 🩵희우

#194 Feat : 설정 화면 뷰 구현
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
  app/src/main/res/drawable/ic_setting_right.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 DESIGN, 🤗 FEATURE, 💛명지

#201 Refactor : 식단 화면 QA 적용 및 수정
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CalendarInterface.kt
  app/src/main/res/layout/fragment_cafeteria.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values/styles.xml
Labels: 🎨 DESIGN, ♻️ REFACTORING, 🩵희우

#199 Refactor : 데이터바인딩 제거
  app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/BindingAdapter.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/OnboardingKeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_onboarding_keyword.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/standard_toolbar.xml
Labels: ♻️ REFACTORING, 💛명지

#208 Hotfix : 식단 주말 안내 제거
  app/src/main/res/layout/fragment_cafeteria.xml
Labels: 🩵희우, 🔥HOTFIX

#206 Feat : 앱 아이콘 및 이름 변경
  app/src/main/AndroidManifest.xml
  app/src/main/ic_logo-playstore.png
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/res/drawable/ic_logo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_logo.webp
  app/src/main/res/mipmap-hdpi/ic_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_logo.webp
  app/src/main/res/mipmap-mdpi/ic_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_logo_round.webp
  app/src/main/res/values/ic_logo_background.xml
  app/src/main/res/values/strings.xml
Labels: 🤗 FEATURE, 💛명지

#209 Feat : 학과 공지 / 검색 공지 중 사용자의 학과 연결
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
Labels: 🤗 FEATURE, 💛명지

#212 Feat : 학과 설정 진입시 이전 학과 활성화
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/DepartRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartViewModel.kt
Labels: 🤗 FEATURE, 🩵희우

#216 Feat : 설정화면 fcm 토큰 관련 api 연동
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/SharedPreference.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/local/dao/KeywordDao.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Setting.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/SettingService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/data/repository/SettingRepository.kt
  app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/di/KoinModules.kt
  app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
  app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
Labels: 🤗 FEATURE, 💛명지
